export const SET_ALL_COUNTS = "SET_ALL_COUNTS";
export const SET_PROVIDER_COUNTS = "SET_PROVIDER_COUNTS";
export const SET_USER_COUNTS = "SET_USER_COUNTS";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_PROFILE = "GET_USER_PROFILE";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_ALL_SUBSCRIPTIONS = "GET_ALL_SUBSCRIPTIONS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_CURRENCY = "GET_ALL_CURRENCY";
export const GET_ALL_REFERRALS = "GET_ALL_REFERRALS";
export const GET_ALL_PAYMENTS = "GET_ALL_PAYMENTS";
export const GET_ALL_ADMINS = "GET_ALL_ADMINS";
export const GET_ALL_PROVIDERS = "GET_ALL_PROVIDERS";
export const GET_ALL_SIGNALS = "GET_ALL_SIGNALS";
export const GET_ALL_BONUS = "GET_ALL_BONUS";
export const GET_ALL_ACCOUNTS = "GET_ALL_ACCOUNTS";
export const GET_ALL_ANNOUNCEMENTS = "GET_ALL_ANNOUNCEMENTS";
export const GET_ALL_PROVIDER_SIGNALS = "GET_ALL_PROVIDER_SIGNALS";
export const GET_ALL_WITHDRAWALS = "GET_ALL_WITHDRAWALS";
export const GET_ALL_WALLETS = "GET_ALL_WALLETS";
export const CLEAR_WALLETS_ACTION = "CLEAR_WALLETS_ACTION";
export const CLEAR_WITHDRAWALS_ACTION = "CLEAR_WITHDRAWALS_ACTION";
export const GET_SEARCH_WITHDRAWALS = "GET_SEARCH_WITHDRAWALS";
export const CLEAR_SEARCH_WITHDRAWALS_ACTION =
  "CLEAR_SEARCH_WITHDRAWALS_ACTION";

export const GET_SEARCH_WALLETS = "GET_SEARCH_WALLETS";
export const CLEAR_SEARCH_WALLETS_ACTION = "CLEAR_SEARCH_WALLETS_ACTION";

export const GET_SEARCH_PROVIDER_SIGNALS = "GET_SEARCH_PROVIDER_SIGNALS";

export const GET_SEARCH_SUBSCRIPTIONS = "GET_SEARCH_SUBSCRIPTIONS";
export const GET_SEARCH_TRANSACTIONS = "GET_SEARCH_TRANSACTIONS";
export const GET_SEARCH_USERS = "GET_SEARCH_USERS";
export const GET_SEARCH_ADMINS = "GET_SEARCH_ADMINS";
export const GET_SEARCH_PROVIDERS = "GET_SEARCH_PROVIDERS";
export const GET_SEARCH_REFERRALS = "GET_SEARCH_REFERRALS";
export const GET_SEARCH_CURRENCY = "GET_SEARCH_CURRENCY";
export const GET_SEARCH_PAYMENTS = "GET_SEARCH_PAYMENTS";
export const GET_SEARCH_BONUS = "GET_SEARCH_BONUS";
export const GET_SEARCH_SIGNALS = "GET_SEARCH_SIGNALS";
export const GET_SEARCH_ACCOUNTS = "GET_SEARCH_ACCOUNTS";
export const GET_SEARCH_ANNOUNCEMENTS = "GET_SEARCH_ANNOUNCEMENTS";

export const ACTION_LOADING = "ACTION_LOADING";

export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const CLEAR_SUBSCRIPTIONS_ACTION = "CLEAR_SUBSCRIPTIONS_ACTION";
export const CLEAR_TRANSACTIONS_ACTION = "CLEAR_TRANSACTIONS_ACTION";
export const CLEAR_REFERRALS_ACTION = "CLEAR_REFERRALS_ACTION";
export const CLEAR_CURRENCY_ACTION = "CLEAR_CURRENCY_ACTION";
export const CLEAR_USERS_ACTION = "CLEAR_USERS_ACTION";
export const CLEAR_BONUS_ACTION = "CLEAR_BONUS_ACTION";
export const CLEAR_ADMINS_ACTION = "CLEAR_ADMINS_ACTION";
export const CLEAR_PROVIDERS_ACTION = "CLEAR_PROVIDERS_ACTION";
export const CLEAR_SIGNALS_ACTION = "CLEAR_SIGNALS_ACTION";
export const CLEAR_ANNOUNCEMENTS_ACTION = "CLEAR_ANNOUNCEMENTS_ACTION";
export const CLEAR_PROVIDER_SIGNALS_ACTION = "CLEAR_PROVIDER_SIGNALS_ACTION";
export const CLEAR_PAYMENTS_ACTION = "CLEAR_PAYMENTS_ACTION";
export const CLEAR_ACCOUNTS_ACTION = "CLEAR_ACCOUNTS_ACTION";
export const CLEAR_ANNOUNCEMENTS_ACTIONS = "CLEAR_ANNOUNCEMENTS_ACTIONS";

export const CLEAR_SEARCH_SUBSCRIPTIONS_ACTION =
  "CLEAR_SEARCH_SUBSCRIPTIONS_ACTION";
export const CLEAR_SEARCH_TRANSACTIONS_ACTION =
  "CLEAR_SEARCH_TRANSACTIONS_ACTION";
export const CLEAR_SEARCH_ADMINS_ACTION = "CLEAR_SEARCH_ADMINS_ACTION";
export const CLEAR_SEARCH_ANNOUNCEMENTS_ACTION =
  "CLEAR_SEARCH_ANNOUNCEMENTS_ACTION";
export const CLEAR_SEARCH_ACCOUNTS_ACTION = "CLEAR_SEARCH_ACCOUNTS_ACTION";
export const CLEAR_SEARCH_SIGNALS_ACTION = "CLEAR_SEARCH_SIGNALS_ACTION";
export const CLEAR_SEARCH_CURRENCY_ACTION = "CLEAR_SEARCH_CURRENCY_ACTION";
export const CLEAR_SEARCH_PAYMENTS_ACTION = "CLEAR_SEARCH_PAYMENTS_ACTION";
export const CLEAR_SEARCH_USERS_ACTION = "CLEAR_SEARCH_USERS_ACTION";
export const CLEAR_SEARCH_REFERRALS_ACTION = "CLEAR_SEARCH_REFERRALS_ACTION";
export const CLEAR_SEARCH_BONUS_ACTION = "CLEAR_SEARCH_BONUS_ACTION";
export const CLEAR_SEARCH_PROVIDERS_ACTION = "CLEAR_SEARCH_PROVIDERS_ACTION";
export const CLEAR_PROVIDERS_SIGNALS_SEARCH = "CLEAR_PROVIDERS_SIGNALS_SEARCH";

export const CLEAR_ALL_ACTIONS = "CLEAR_ALL_ACTIONS";
export const CLEAR_ALL_SEARCH_ACTIONS = "CLEAR_ALL_SEARCH_ACTIONS";

export const GET_USER_SIGNALS = "GET_USER_SIGNALS";
export const CLEAR_USER_SIGNALS_ACTION = "CLEAR_USER_SIGNALS_ACTION";
export const GET_USER_SEARCH_SIGNALS = "GET_USER_SEARCH_SIGNALS";
export const CLEAR_USERS_SIGNALS_SEARCH = "CLEAR_USERS_SIGNALS_SEARCH";
export const GET_USER_REFERRALS = "GET_USER_REFERRALS";
export const CLEAR_USER_REFERRALS_ACTION = "CLEAR_USER_REFERRALS_ACTION";
export const GET_USER_SEARCH_REFERRALS = "GET_USER_SEARCH_REFERRALS";
export const CLEAR_USERS_REFERRALS_SEARCH = "CLEAR_USERS_REFERRALS_SEARCH";
export const GET_USER_SUBSCRIPTIONS = "GET_USER_SUBSCRIPTIONS";
export const CLEAR_USER_SUBSCRIPTIONS_ACTION =
  "CLEAR_USER_SUBSCRIPTIONS_ACTION";
export const GET_USER_SEARCH_SUBSCRIPTIONS = "GET_USER_SEARCH_SUBSCRIPTIONS";
export const CLEAR_USERS_SUBSCRIPTIONS_SEARCH =
  "CLEAR_USERS_SUBSCRIPTIONS_SEARCH";
export const GET_USER_TRANSACTIONS = "GET_USER_TRANSACTIONS";
export const CLEAR_USER_TRANSACTIONS_ACTION = "CLEAR_USER_TRANSACTIONS_ACTION";
export const GET_USER_SEARCH_TRANSACTIONS = "GET_USER_SEARCH_TRANSACTIONS";
export const CLEAR_USERS_TRANSACTIONS_SEARCH =
  "CLEAR_USERS_TRANSACTIONS_SEARCH";

export const GET_USER_PAYMENTS = "GET_USER_PAYMENTS";
export const CLEAR_USER_PAYMENTS_ACTION = "CLEAR_USER_PAYMENTS_ACTION";
export const GET_USER_SEARCH_PAYMENTS = "GET_USER_SEARCH_PAYMENTS";
export const CLEAR_USERS_PAYMENTS_SEARCH = "CLEAR_USERS_PAYMENTS_SEARCH";

export const GET_USER_WITHDRAWALS = "GET_USER_WITHDRAWALS";
export const CLEAR_USER_WITHDRAWALS_ACTION = "CLEAR_USER_WITHDRAWALS_ACTION";
export const GET_USER_SEARCH_WITHDRAWALS = "GET_USER_SEARCH_WITHDRAWALS";
export const CLEAR_USERS_WITHDRAWALS_SEARCH = "CLEAR_USERS_WITHDRAWALS_SEARCH";

export const GET_USER_BONUS = "GET_USER_BONUS";
export const CLEAR_USER_BONUS_ACTION = "CLEAR_USER_BONUS_ACTION";
export const GET_USER_SEARCH_BONUS = "GET_USER_SEARCH_BONUS";
export const CLEAR_USERS_BONUS_SEARCH = "CLEAR_USERS_BONUS_SEARCH";

export const USER_CONFIRM_PASSWORD_ACTION = "USER_CONFIRM_PASSWORD_ACTION";
export const CLEAR_USER_CONFIRM_PASSWORD_ACTION =
  "CLEAR_USER_CONFIRM_PASSWORD_ACTION";

export const USER_RESET_PASSWORD_ACTION = "USER_RESET_PASSWORD_ACTION";
export const CLEAR_USER_RESET_PASSWORD_ACTION =
  "CLEAR_USER_RESET_PASSWORD_ACTION";

export const GET_ALL_CURRENCY_PAIR = "GET_ALL_CURRENCY_PAIR";
export const CLEAR_GET_ALL_CURRENCY_PAIR = "CLEAR_GET_ALL_CURRENCY_PAIR";

export const ADD_NEW_SIGNAL = "ADD_NEW_SIGNAL";
export const CLEAR_ADD_NEW_SIGNAL = "CLEAR_ADD_NEW_SIGNAL";

export const EDIT_NEW_SIGNAL = "EDIT_NEW_SIGNAL";
export const CLEAR_EDIT_NEW_SIGNAL = "CLEAR_EDIT_NEW_SIGNAL";

export const ADD_NEW_CURRENCY = "ADD_NEW_CURRENCY";
export const CLEAR_ADD_NEW_CURRENCY = "CLEAR_ADD_NEW_CURRENCY";

export const UPDATE_CURRENCY = "UPDATE_CURRENCY";
export const CLEAR_UPDATE_CURRENCY = "CLEAR_UPDATE_CURRENCY";

export const UPDATE_WALLET = "UPDATE_WALLET";
export const CLEAR_UPDATE_WALLET = "CLEAR_UPDATE_WALLET";

export const UPDATE_WITHDRAWALS = "UPDATE_WITHDRAWALS";
export const CLEAR_UPDATE_WITHDRAWALS = "CLEAR_UPDATE_WITHDRAWALS";

export const ADD_NEW_ADMIN = "ADD_NEW_ADMIN";
export const CLEAR_ADD_NEW_ADMIN = "CLEAR_ADD_NEW_ADMIN";

export const ADD_NEW_PROVIDER = "ADD_NEW_PROVIDER";
export const CLEAR_ADD_NEW_PROVIDER = "CLEAR_ADD_NEW_PROVIDER";

export const UPDATE_ADMIN = "UPDATE_ADMIN";
export const CLEAR_UPDATE_ADMIN = "CLEAR_UPDATE_ADMIN";

export const UPDATE_BONUS = "UPDATE_BONUS";
export const CLEAR_UPDATE_BONUS = "CLEAR_UPDATE_BONUS";

export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const CLEAR_DELETE_ANNOUNCEMENT = "CLEAR_DELETE_ANNOUNCEMENT";

export const ADD_ANNOUNCEMENT = "ADD_ANNOUNCEMENT";
export const CLEAR_ADD_ANNOUNCEMENT = "CLEAR_ADD_ANNOUNCEMENT";

export const EDIT_ANNOUNCEMENT = "EDIT_ANNOUNCEMENT";
export const CLEAR_EDIT_ANNOUNCEMENT = "CLEAR_EDIT_ANNOUNCEMENT";

export const GET_PREMIUM_STATUS = "GET_PREMIUM_STATUS";
export const CLEAR_GET_PREMIUM_STATUS = "CLEAR_GET_PREMIUM_STATUS";

export const GET_DASHBOARD_DETAILS = "GET_DASHBOARD_DETAILS";
export const CLEAR_GET_DASHBOARD_DETAILS = "CLEAR_GET_DASHBOARD_DETAILS";

export const GET_USER_SETTINGS = "GET_SETTINGS";
export const CLEAR_GET_USER_SETTINGS = "CLEAR_GET_SETTINGS";

export const GET_ADMIN_SETTINGS = "GET_ADMIN_SETTINGS";
export const CLEAR_GET_ADMIN_SETTINGS = "CLEAR_GET_ADMIN_SETTINGS";

export const GET_PROVIDER_SETTINGS = "GET_PROVIDER_SETTINGS";
export const CLEAR_GET_PROVIDER_SETTINGS = "CLEAR_GET_PROVIDER_SETTINGS";

export const USER_GET_CURRENCY = "USER_GET_CURRENCY";
export const CLEAR_USER_GET_CURRENCY = "CLEAR_USER_GET_CURRENCY";

export const USER_GET_PROVIDERS = "USER_GET_PROVIDERS";
export const CLEAR_USER_GET_PROVIDERS = "CLEAR_USER_GET_PROVIDERS";

export const USER_GET_WALLET = "USER_GET_WALLET";
export const CLEAR_USER_GET_WALLET = "CLEAR_USER_GET_WALLET";

export const USER_SET_CURRENCY = "USER_SET_CURRENCY";
export const CLEAR_USER_SET_CURRENCY = "CLEAR_USER_SET_CURRENCY";

export const USER_UPDATE_CURRENCY = "USER_UPDATE_CURRENCY";
export const CLEAR_USER_UPDATE_CURRENCY = "CLEAR_USER_UPDATE_CURRENCY";

export const USER_SET_PROVIDERS = "USER_SET_PROVIDERS";
export const CLEAR_USER_SET_PROVIDERS = "CLEAR_USER_SET_PROVIDERS";

export const USER_UPDATE_PROVIDERS = "USER_UPDATE_PROVIDERS";
export const CLEAR_USER_UPDATE_PROVIDERS = "CLEAR_USER_UPDATE_PROVIDERS";

export const USER_UPDATE_NOTIFY = "USER_UPDATE_NOTIFY";
export const CLEAR_USER_UPDATE_NOTIFY = "CLEAR_USER_UPDATE_NOTIFY";

export const USER_UPDATE_MODE = "USER_UPDATE_MODE";
export const CLEAR_USER_UPDATE_MODE = "CLEAR_USER_UPDATE_MODE";

export const USER_UPDATE_PROFILE = "USER_UPDATE_PROFILE";
export const CLEAR_USER_UPDATE_PROFILE = "CLEAR_USER_UPDATE_PROFILE";

export const USER_UPDATE_ACCOUNT = "USER_UPDATE_ACCOUNT";
export const CLEAR_USER_UPDATE_ACCOUNT = "CLEAR_USER_UPDATE_ACCOUNT";

export const USER_UPDATE_PASSWORD = "USER_UPDATE_PASSWORD";
export const CLEAR_USER_UPDATE_PASSWORD = "CLEAR_USER_UPDATE_PASSWORD";

export const ADMIN_UPDATE_MODE = "ADMIN_UPDATE_MODE";
export const CLEAR_ADMIN_UPDATE_MODE = "CLEAR_ADMIN_UPDATE_MODE";

export const ADMIN_UPDATE_PROFILE = "ADMIN_UPDATE_PROFILE";
export const CLEAR_ADMIN_UPDATE_PROFILE = "CLEAR_ADMIN_UPDATE_PROFILE";

export const ADMIN_UPDATE_PASSWORD = "ADMIN_UPDATE_PASSWORD";
export const CLEAR_ADMIN_UPDATE_PASSWORD = "CLEAR_ADMIN_UPDATE_PASSWORD";

export const PROVIDER_UPDATE_MODE = "PROVIDER_UPDATE_MODE";
export const CLEAR_PROVIDER_UPDATE_MODE = "CLEAR_PROVIDER_UPDATE_MODE";

export const PROVIDER_UPDATE_PROFILE = "PROVIDER_UPDATE_PROFILE";
export const CLEAR_PROVIDER_UPDATE_PROFILE = "CLEAR_PROVIDER_UPDATE_PROFILE";

export const PROVIDER_UPDATE_PASSWORD = "PROVIDER_UPDATE_PASSWORD";
export const CLEAR_PROVIDER_UPDATE_PASSWORD = "CLEAR_PROVIDER_UPDATE_PASSWORD";

export const ADMIN_ADD_WALLET = "ADMIN_ADD_WALLET";
export const CLEAR_ADMIN_ADD_WALLET = "CLEAR_ADMIN_ADD_WALLET";

export const USER_GET_BALANCE = "USER_GET_BALANCE";
export const CLEAR_USER_GET_BALANCE = "CLEAR_USER_GET_BALANCE";

export const USER_GET_ACCOUNT = "USER_GET_ACCOUNT";
export const CLEAR_USER_GET_ACCOUNT = "CLEAR_USER_GET_ACCOUNT";

export const USER_REQUEST_WITHDRAWAL = "USER_REQUEST_WITHDRAWAL";
export const CLEAR_USER_REQUEST_WITHDRAWAL = "CLEAR_USER_REQUEST_WITHDRAWAL";

export const USER_GET_FORUM = "USER_GET_FORUM";
export const CLEAR_USER_GET_FORUM = "CLEAR_USER_GET_FORUM";

export const USER_SEARCH_FORUM = "USER_SEARCH_FORUM";
export const CLEAR_USER_SEARCH_FORUM = "CLEAR_USER_SEARCH_FORUM";

export const USER_ADD_FORUM = "USER_ADD_FORUM";
export const CLEAR_USER_ADD_FORUM = "CLEAR_USER_ADD_FORUM";

export const USER_UPDATE_FORUM = "USER_UPDATE_FORUM";
export const CLEAR_USER_UPDATE_FORUM = "CLEAR_USER_UPDATE_FORUM";

export const USER_GET_A_FORUM = "USER_GET_A_FORUM";
export const CLEAR_USER_GET_A_FORUM = "CLEAR_USER_GET_A_FORUM";

export const USER_REPLY = "USER_REPLY";
export const CLEAR_USER_REPLY = "CLEAR_USER_REPLY";

export const USER_DELETE_REPLY = "USER_DELETE_REPLY";
export const CLEAR_USER_DELETE_REPLY = "CLEAR_USER_DELETE_REPLY";

export const ADMIN_GET_USER = "ADMIN_GET_USER";
export const CLEAR_ADMIN_GET_USER = "CLEAR_ADMIN_GET_USER";

export const ADMIN_GET_SUB = "ADMIN_GET_SUB";
export const CLEAR_ADMIN_GET_SUB = "CLEAR_ADMIN_GET_SUB";

export const ADMIN_GET_FORUM = "ADMIN_GET_FORUM";
export const CLEAR_ADMIN_GET_FORUM = "CLEAR_ADMIN_GET_FORUM";

export const ADMIN_SEARCH_FORUM = "ADMIN_SEARCH_FORUM";
export const CLEAR_ADMIN_SEARCH_FORUM = "CLEAR_ADMIN_SEARCH_FORUM";

export const ADMIN_ADD_FORUM = "ADMIN_ADD_FORUM";
export const CLEAR_ADMIN_ADD_FORUM = "CLEAR_ADMIN_ADD_FORUM";

export const ADMIN_UPDATE_FORUM = "ADMIN_UPDATE_FORUM";
export const CLEAR_ADMIN_UPDATE_FORUM = "CLEAR_ADMIN_UPDATE_FORUM";

export const ADMIN_GET_A_FORUM = "ADMIN_GET_A_FORUM";
export const CLEAR_ADMIN_GET_A_FORUM = "CLEAR_ADMIN_GET_A_FORUM";

export const ADMIN_REPLY = "ADMIN_REPLY";
export const CLEAR_ADMIN_REPLY = "CLEAR_ADMIN_REPLY";

export const ADMIN_DELETE_REPLY = "ADMIN_DELETE_REPLY";
export const CLEAR_ADMIN_DELETE_REPLY = "CLEAR_ADMIN_DELETE_REPLY";

export const ADMIN_GET_A_BONUS = "ADMIN_GET_A_BONUS";
export const CLEAR_ADMIN_GET_A_BONUS = "CLEAR_ADMIN_GET_A_BONUS";

export const ADMIN_GET_AN_ADMIN = "ADMIN_GET_AN_ADMIN";
export const CLEAR_ADMIN_GET_AN_ADMIN = "CLEAR_ADMIN_GET_AN_ADMIN";

export const ADMIN_GET_A_USER = "ADMIN_GET_A_USER";
export const CLEAR_ADMIN_GET_A_USER = "CLEAR_ADMIN_GET_A_USER";

export const PROVIDER_GET_FOLLOWERS = "PROVIDER_GET_FOLLOWERS";
export const CLEAR_PROVIDER_GET_FOLLOWERS = "CLEAR_PROVIDER_GET_FOLLOWERS";

export const ADMIN_CHANGE_EMAIL = "ADMIN_CHANGE_EMAIL";
export const CLEAR_ADMIN_CHANGE_EMAIL = "CLEAR_ADMIN_CHANGE_EMAIL";
