export const SET_ALL_COUNTS = "SET_ALL_COUNTS";
export const SET_PROVIDER_COUNTS = "SET_PROVIDER_COUNTS";
export const SET_USER_COUNTS = "SET_USER_COUNTS";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_PROFILE = "GET_USER_PROFILE";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_ALL_SUBSCRIPTIONS = "GET_ALL_SUBSCRIPTIONS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_CURRENCY = "GET_ALL_CURRENCY";
export const GET_ALL_REFERRALS = "GET_ALL_REFERRALS";
export const GET_ALL_PAYMENTS = "GET_ALL_PAYMENTS";
export const GET_ALL_ADMINS = "GET_ALL_ADMINS";
export const GET_ALL_PROVIDERS = "GET_ALL_PROVIDERS";
export const GET_ALL_SIGNALS = "GET_ALL_SIGNALS";
export const GET_ALL_BONUS = "GET_ALL_BONUS";
export const GET_ALL_ACCOUNTS = "GET_ALL_ACCOUNTS";
export const GET_ALL_ANNOUNCEMENTS = "GET_ALL_ANNOUNCEMENTS";
export const GET_ALL_PROVIDER_SIGNALS = "GET_ALL_PROVIDER_SIGNALS";

export const GET_SEARCH_PROVIDER_SIGNALS = "GET_SEARCH_PROVIDER_SIGNALS";

export const GET_SEARCH_SUBSCRIPTIONS = "GET_SEARCH_SUBSCRIPTIONS";
export const GET_SEARCH_TRANSACTIONS = "GET_SEARCH_TRANSACTIONS";
export const GET_SEARCH_USERS = "GET_SEARCH_USERS";
export const GET_SEARCH_ADMINS = "GET_SEARCH_ADMINS";
export const GET_SEARCH_PROVIDERS = "GET_SEARCH_PROVIDERS";
export const GET_SEARCH_REFERRALS = "GET_SEARCH_REFERRALS";
export const GET_SEARCH_CURRENCY = "GET_SEARCH_CURRENCY";
export const GET_SEARCH_PAYMENTS = "GET_SEARCH_PAYMENTS";
export const GET_SEARCH_BONUS = "GET_SEARCH_BONUS";
export const GET_SEARCH_SIGNALS = "GET_SEARCH_SIGNALS";
export const GET_SEARCH_ACCOUNTS = "GET_SEARCH_ACCOUNTS";
export const GET_SEARCH_ANNOUNCEMENTS = "GET_SEARCH_ANNOUNCEMENTS";

export const ACTION_LOADING = "ACTION_LOADING";

export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const CLEAR_SUBSCRIPTIONS_ACTION = "CLEAR_SUBSCRIPTIONS_ACTION";
export const CLEAR_TRANSACTIONS_ACTION = "CLEAR_TRANSACTIONS_ACTION";
export const CLEAR_REFERRALS_ACTION = "CLEAR_REFERRALS_ACTION";
export const CLEAR_CURRENCY_ACTION = "CLEAR_CURRENCY_ACTION";
export const CLEAR_USERS_ACTION = "CLEAR_USERS_ACTION";
export const CLEAR_BONUS_ACTION = "CLEAR_BONUS_ACTION";
export const CLEAR_ADMINS_ACTION = "CLEAR_ADMINS_ACTION";
export const CLEAR_PROVIDERS_ACTION = "CLEAR_PROVIDERS_ACTION";
export const CLEAR_SIGNALS_ACTION = "CLEAR_SIGNALS_ACTION";
export const CLEAR_ANNOUNCEMENTS_ACTION = "CLEAR_ANNOUNCEMENTS_ACTION";
export const CLEAR_PROVIDER_SIGNALS_ACTION = "CLEAR_PROVIDER_SIGNALS_ACTION";
export const CLEAR_PAYMENTS_ACTION = "CLEAR_PAYMENTS_ACTION";
export const CLEAR_ACCOUNTS_ACTION = "CLEAR_ACCOUNTS_ACTION";
export const CLEAR_ANNOUNCEMENTS_ACTIONS = "CLEAR_ANNOUNCEMENTS_ACTIONS";

export const CLEAR_SEARCH_SUBSCRIPTIONS_ACTION =
  "CLEAR_SEARCH_SUBSCRIPTIONS_ACTION";
export const CLEAR_SEARCH_TRANSACTIONS_ACTION =
  "CLEAR_SEARCH_TRANSACTIONS_ACTION";
export const CLEAR_SEARCH_ADMINS_ACTION = "CLEAR_SEARCH_ADMINS_ACTION";
export const CLEAR_SEARCH_ANNOUNCEMENTS_ACTION =
  "CLEAR_SEARCH_ANNOUNCEMENTS_ACTION";
export const CLEAR_SEARCH_ACCOUNTS_ACTION = "CLEAR_SEARCH_ACCOUNTS_ACTION";
export const CLEAR_SEARCH_SIGNALS_ACTION = "CLEAR_SEARCH_SIGNALS_ACTION";
export const CLEAR_SEARCH_CURRENCY_ACTION = "CLEAR_SEARCH_CURRENCY_ACTION";
export const CLEAR_SEARCH_PAYMENTS_ACTION = "CLEAR_SEARCH_PAYMENTS_ACTION";
export const CLEAR_SEARCH_USERS_ACTION = "CLEAR_SEARCH_USERS_ACTION";
export const CLEAR_SEARCH_REFERRALS_ACTION = "CLEAR_SEARCH_REFERRALS_ACTION";
export const CLEAR_SEARCH_BONUS_ACTION = "CLEAR_SEARCH_BONUS_ACTION";
export const CLEAR_SEARCH_PROVIDERS_ACTION = "CLEAR_SEARCH_PROVIDERS_ACTION";
export const CLEAR_PROVIDERS_SIGNALS_SEARCH = "CLEAR_PROVIDERS_SIGNALS_SEARCH";

export const CLEAR_ALL_ACTIONS = "CLEAR_ALL_ACTIONS";
export const CLEAR_ALL_SEARCH_ACTIONS = "CLEAR_ALL_SEARCH_ACTIONS";

export const GET_USER_SIGNALS = "GET_USER_SIGNALS";
export const CLEAR_USER_SIGNALS_ACTION = "CLEAR_USER_SIGNALS_ACTION";
export const GET_USER_SEARCH_SIGNALS = "GET_USER_SEARCH_SIGNALS";
export const CLEAR_USERS_SIGNALS_SEARCH = "CLEAR_USERS_SIGNALS_SEARCH";
export const GET_USER_REFERRALS = "GET_USER_REFERRALS";
export const CLEAR_USER_REFERRALS_ACTION = "CLEAR_USER_REFERRALS_ACTION";
export const GET_USER_SEARCH_REFERRALS = "GET_USER_SEARCH_REFERRALS";
export const CLEAR_USERS_REFERRALS_SEARCH = "CLEAR_USERS_REFERRALS_SEARCH";
export const GET_USER_SUBSCRIPTIONS = "GET_USER_SUBSCRIPTIONS";
export const CLEAR_USER_SUBSCRIPTIONS_ACTION =
  "CLEAR_USER_SUBSCRIPTIONS_ACTION";
export const GET_USER_SEARCH_SUBSCRIPTIONS = "GET_USER_SEARCH_SUBSCRIPTIONS";
export const CLEAR_USERS_SUBSCRIPTIONS_SEARCH =
  "CLEAR_USERS_SUBSCRIPTIONS_SEARCH";
export const GET_USER_TRANSACTIONS = "GET_USER_TRANSACTIONS";
export const CLEAR_USER_TRANSACTIONS_ACTION = "CLEAR_USER_TRANSACTIONS_ACTION";
export const GET_USER_SEARCH_TRANSACTIONS = "GET_USER_SEARCH_TRANSACTIONS";
export const CLEAR_USERS_TRANSACTIONS_SEARCH =
  "CLEAR_USERS_TRANSACTIONS_SEARCH";

export const GET_USER_PAYMENTS = "GET_USER_PAYMENTS";
export const CLEAR_USER_PAYMENTS_ACTION = "CLEAR_USER_PAYMENTS_ACTION";
export const GET_USER_SEARCH_PAYMENTS = "GET_USER_SEARCH_PAYMENTS";
export const CLEAR_USERS_PAYMENTS_SEARCH = "CLEAR_USERS_PAYMENTS_SEARCH";
