export const TEXT_DISPATCH = "TEXT_DISPATCH";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_ALL_SUBSCRIPTIONS = "GET_ALL_SUBSCRIPTIONS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_SEARCH_SUBSCRIPTIONS = "GET_SEARCH_SUBSCRIPTIONS";
export const GET_SEARCH_TRANSACTIONS = "GET_SEARCH_TRANSACTIONS";
export const GET_SEARCH_USERS = "GET_SEARCH_USERS";
export const ACTION_LOADING = "ACTION_LOADING";
export const CLEAR_SUBSCRIPTIONS_ACTION = "CLEAR_SUBSCRIPTIONS_ACTION";
export const CLEAR_TRANSACTIONS_ACTION = "CLEAR_TRANSACTIONS_ACTION";
export const CLEAR_USERS_ACTION = "CLEAR_USERS_ACTION";
export const GET_SUBSCRIPTION_COUNT = "GET_SUBSCRIPTION_COUNT";
export const CLEAR_SEARCH_SUBSCRIPTIONS_ACTION =
  "CLEAR_SEARCH_SUBSCRIPTIONS_ACTION";
export const CLEAR_SEARCH_TRANSACTIONS_ACTION =
  "CLEAR_SEARCH_TRANSACTIONS_ACTION";
export const CLEAR_SEARCH_USERS_ACTION = "CLEAR_SEARCH_USERS_ACTION";
